version: "3"
services:
  springmongodb:
    image: mongo:latest
    container_name: springmongodb
    ports:
      - 27017:27017

  order-service:
    image: order-service:1.0
    container_name: order-service
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    depends_on:
      - springmongodb

  product-service:
    image: product-service:1.0
    container_name: product-service
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
    depends_on:
      - springmongodb

  user-service:
    image: user-service:1.0
    container_name: user-service
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
    depends_on:
      - springmongodb
